name: user_service
description: A service to handle user authentication
version: 0.1.0
# homepage: https://www.example.com
# author: marco <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  rxdart: ^0.19.0

dev_dependencies:
  test: ^1.0.0
